data:
#  dir: "/Users/kavya/Documents/Master-Thesis/Underwater-Segmentation/data/segmentation/simple_cod_subset"
  dir: "/home/rveeramalli/ufo-segmentation/data_v1" # Directory for data with manually labelled target masks
  idx_dir: "/home/rveeramalli/ufo-segmentation/data_v1/indices_ufs" # Directory to store train-val-test split indices
  bbox_dir: "/home/rveeramalli/ufo-segmentation/data/simple_cod_subset/ground-truth" # Bounding box coordinates for the images.
  UFS: # Underwater Fish Segmentation Dataset
    images: "images" # Name of images directory
    labels: "masks" # Name of masks directory
    output: "box_overlay"
  kitti: # KITTI VISION Benchmark Dataset
    images: "image_2"
    labels: "semantic"
  width: 720 # Width of the input image to the model
  height: 360 # Height of the input image to the model
  eval_path: "/home/rveeramalli/ufo-segmentation/data_v1/eval" # Path for model evaluation on test data
  rescale: "bbox" # Mode bbox or normal

model:
  pspnet:
    encoder_name: "mobilenet_v2"
    in_channels: 1 # Inputs are grauscale images
    activation: "sigmoid"
    encoder_weights: "imagenet"

train:
  training: 1 # Mode training or evaluationg
  batch_size: 4  # batch size for training
  optimizer: "adam"  # optimizer for training
  lr: 0.001  # learning rate for the optimizer
  gpus: 1  # number of gpus to use in training
  check_val_every_n_epoch: 1  # how often should validation be checked for early stopping
  max_epochs: 100  # maximum number of training epochs
  precision: 32  # bit precision for use in training, either 32 or 16
  saved_model_path: "/home/rveeramalli/ufo-segmentation/src/saved_models" # Path to store trained models

early_stopping:
  metric: "validation/loss"  # metric for early stopping criterion
  min_delta: 0.00  # minimum delta expected for early stopping
  mode: "min"  # is the metric supposed to go down or up
  patience: 3  # how many epochs do we wait before stopping
